# Generated by Django 5.0 on 2023-12-18 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='hours_worked_month',
            field=models.IntegerField(default=0, verbose_name='Hours Worked in Month'),
        ),
        migrations.AddField(
            model_name='doctors',
            name='month',
            field=models.CharField(default='December', max_length=10, verbose_name='Month'),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
